🧹 Déplacement de l'app Symfony à la racine du projet

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,7 +47,13 @@ jobs:
         run: composer install --prefer-dist
 
       - name: Run PHPUnit
-        run: vendor/bin/phpunit --testdox
+        run: |
+            if [ -f vendor/bin/phpunit ]; then
+            vendor/bin/phpunit --testdox
+            else
+            echo "PHPUnit not found"; exit 1
+            fi
+
 
   deploy:
     name: 🚀 Deploy to Plesk
